### ISSUE TITLE
Issuing building for Windows with scons

### ISSUE THREAD

**Issue by bparisf** [RossMeikleham/PlutoBoy#49]
Hello,

Apologies for the noob question, but I don't know why I can't build an executable for Windows. When I go and enter `scons` in cmd on the `build/Windows/scons` folder, a file called `scons.py` is simply opened in Visual Studio. Do I need to run this somehow? I'm not at all familiar with Scons.

Cheers

**Comment by RossMeikleham** [comment]
Sorry, not sure how your Scons is setup to cause that. Due to how WIndows is its hard to make it really easy for someone to build for themselves, since Docker for Windows still requires some setup and certain versions of Windows 10 due to HyperV. 

I've moved the CI over to Github Actions from Travis and this now outputs binaries so you don't have to build them yourself, e.g. https://github.com/RossMeikleham/PlutoBoy/actions/runs/490827330
